site_name: 'Knowledge Base'
site_description: 'Knowledge Base for developers and customers.'
site_author: 'AIMWARE'
copyright: '© 2021 AIMWARE. All rights reserved.'
repo_url: https://github.com/AMWRNET/aimware-web-kb
edit_uri: edit/master/private/

docs_dir: 'private'
site_dir: 'public/kb'

nav:
    - Home: index.md

    - Lua:
        - Introduction: lua/introduction.md
        - Load a script: lua/load-script.md
        - Register a callback: lua/register-callbacks.md

        - Documentation:
            - Callbacks: lua/docs/callbacks.md
            - Globals:
                - GetScriptName: lua/docs/globals/getscriptname.md
                - LoadScript: lua/docs/globals/loadscript.md
                - UnloadScript: lua/docs/globals/unloadscript.md
                - RunScript: lua/docs/globals/runscript.md
                - Print: lua/docs/globals/print.md
            - Classes:
                - EulerAngles: lua/docs/class/eulerangles.md
                - Material: lua/docs/class/material.md
                - File: lua/docs/class/file.md
                - Font: lua/docs/class/font.md
                - GuiObject: lua/docs/class/guiobject.md
                - Socket: lua/docs/class/socket.md
                - Texture: lua/docs/class/texture.md
                - Vector3: lua/docs/class/vector3.md
            - Libraries:
                - Cheat:
                    - IsFakeDucking: lua/docs/library/cheat/isfakeducking.md
                    - RequestSpeedBurst: lua/docs/library/cheat/requestspeedburst.md
                - Entities: lua/docs/library/entities.md
                - Panorama: lua/docs/library/panorama.md
                - Materials: lua/docs/library/materials.md
                - Input:
                    - GetMousePos: lua/docs/library/input/getmousepos.md
                    - IsButtonDown: lua/docs/library/input/isbuttondown.md
                    - IsButtonPressed: lua/docs/library/input/isbuttonpressed.md
                    - IsButtonReleased: lua/docs/library/input/isbuttonreleased.md
                    - GetMouseWheelDelta: lua/docs/library/input/getmousewheeldelta.md
                    - Keylist: lua/docs/library/input/keylist.md
                - Callbacks:
                    - Register: lua/docs/library/callbacks/register.md
                    - Unregister: lua/docs/library/callbacks/unregister.md
                - Common:
                    - Time: lua/docs/library/common/time.md
                    - DecodePNG: lua/docs/library/common/decodepng.md
                    - DecodeJPEG: lua/docs/library/common/decodejpeg.md
                    - RasterizeSVG: lua/docs/library/common/rasterizesvg.md
                - Draw:
                    - Examples:
                        - RectAnimation: lua/docs/library/draw/examples/rectanimation.md
                    - Color: lua/docs/library/draw/color.md
                    - Line: lua/docs/library/draw/line.md
                    - FilledRect: lua/docs/library/draw/filledrect.md
                    - OutlinedRect: lua/docs/library/draw/outlinedrect.md
                    - RoundedRect: lua/docs/library/draw/roundedrect.md
                    - RoundedRectFill: lua/docs/library/draw/roundedrectfill.md
                    - ShadowRect: lua/docs/library/draw/shadowrect.md
                    - Triangle: lua/docs/library/draw/triangle.md
                    - FilledCircle: lua/docs/library/draw/filledcircle.md
                    - OutlinedCircle: lua/docs/library/draw/outlinedcircle.md
                    - GetTextSize: lua/docs/library/draw/gettextsize.md
                    - Text: lua/docs/library/draw/text.md
                    - TextShadow: lua/docs/library/draw/textshadow.md
                    - GetScreenSize: lua/docs/library/draw/getscreensize.md
                    - CreateFont: lua/docs/library/draw/createfont.md
                    - AddFontResource: lua/docs/library/draw/addfontresource.md
                    - SetFont: lua/docs/library/draw/setfont.md
                    - Fontlist: lua/docs/library/draw/fontlist.md
                    - CreateTexture: lua/docs/library/draw/createtexture.md
                    - UpdateTexture: lua/docs/library/draw/updatetexture.md
                    - SetTexture: lua/docs/library/draw/settexture.md
                    - SetScissorRect: lua/docs/library/draw/setscissorrect.md
                - File:
                    - Open: lua/docs/library/file/open.md
                    - Delete: lua/docs/library/file/delete.md
                    - Enumerate: lua/docs/library/file/enumerate.md
                    - Read: lua/docs/library/file/read.md
                    - Write: lua/docs/library/file/write.md
                - Gui:
                    - Reference: lua/docs/library/gui/reference.md
                    - XML: lua/docs/library/gui/reference.md
                    - Elements: lua/docs/library/gui/elements.md
                    - Attributes: lua/docs/library/gui/attributes.md
                    - Button: lua/docs/library/gui/button.md
                    - RadioButton: lua/docs/library/gui/radiobutton.md
                    - Checkbox: lua/docs/library/gui/checkbox.md
                    - Color Picker: lua/docs/library/gui/colorpicker.md
                    - Combobox: lua/docs/library/gui/combobox.md
                    - Command: lua/docs/library/gui/command.md
                    - Custom: lua/docs/library/gui/custom.md
                    - Editbox: lua/docs/library/gui/editbox.md
                    - Groupbox: lua/docs/library/gui/groupbox.md
                    - Keybox: lua/docs/library/gui/keybox.md
                    - Listbox: lua/docs/library/gui/listbox.md
                    - Multibox: lua/docs/library/gui/multibox.md
                    - Slider: lua/docs/library/gui/slider.md
                    - Tab: lua/docs/library/gui/tab.md
                    - Tablist: lua/docs/library/gui/tablist.md
                    - Text: lua/docs/library/gui/text.md
                    - Window: lua/docs/library/gui/window.md
                - HTTP:
                    - Get: lua/docs/library/http/get.md
                - Network:
                    - Socket: lua/docs/library/network/socket.md
                    - GetAddrInfo: lua/docs/library/network/getaddrinfo.md
                    - GetNameInfo: lua/docs/library/network/getnameinfo.md
                - Vector:
                    - Vector: lua/docs/library/vector.md
            - Engine Specific:
                  - Source:
                        - Callbacks: lua/docs/engine/source/callbacks.md
                        - Classes:
                            - DrawModelContext: lua/docs/engine/source/class/drawmodelcontext.md
                            - EspBuilder: lua/docs/engine/source/class/espbuilder.md
                            - Entity: lua/docs/engine/source/class/entity.md
                            - GameEvent: lua/docs/engine/source/class/gameevent.md
                            - StringCmd: lua/docs/engine/source/class/stringcmd.md
                            - Trace: lua/docs/engine/source/class/trace.md
                            - UserCmd: lua/docs/engine/source/class/usercmd.md
                            - UserMessage: lua/docs/engine/source/class/usermessage.md
                        - Libraries:
                            - Engine:
                                - GetMapName: lua/docs/engine/source/library/engine/getmapname.md
                                - GetPointsContent: lua/docs/engine/source/library/engine/getpointscontent.md
                                - TraceHull: lua/docs/engine/source/library/engine/tracehull.md
                                - TraceLine: lua/docs/engine/source/library/engine/traceline.md
        - Examples: lua/examples.md

theme:
    name: material
    favicon: 'https://aimware.net/favicon.ico'
    palette:
        scheme: slate
        primary: red
        accent: red

plugins:
    - search

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
