site_name: 'Knowledge Base'
site_description: 'Knowledge Base for developers and customers.'
site_author: 'AIMWARE'
copyright: '© 2021 AIMWARE. All rights reserved.'
repo_url: https://github.com/AMWRNET/aimware-web-kb
edit_uri: edit/master/private/

docs_dir: 'private'
site_dir: 'public/kb'

nav:
    - Home: index.md

    - Lua:
        - Introduction: lua/introduction.md
        - Load a script: lua/load-script.md
        - Register a callback: lua/register-callbacks.md

        - Documentation:
            - Callbacks: lua/docs/callbacks.md
            - Globals:
                - GetScriptName: lua/docs/globals/getscriptname.md
                - LoadScript: lua/docs/globals/loadscript.md
                - UnloadScript: lua/docs/globals/unloadscript.md
                - RunScript: lua/docs/globals/runscript.md
                - Print: lua/docs/globals/print.md
            - Classes:
                - EspBuilder: lua/docs/class/espbuilder.md
                - EulerAngles: lua/docs/class/eulerangles.md
                - File: lua/docs/class/file.md
                - Font: lua/docs/class/font.md
                - GuiObject: lua/docs/class/guiobject.md
                - Socket: lua/docs/class/socket.md
                - Texture: lua/docs/class/texture.md
                - Vector3: lua/docs/class/vector3.md
                - Entity: lua/docs/class/entity.md
                - GameEvent: lua/docs/class/gameevent.md
                - UserCmd: lua/docs/class/usercmd.md
                - UserMessage: lua/docs/class/usermessage.md
                - DrawModelContext: lua/docs/class/drawmodelcontext.md
            - Libraries:
                - Entities: lua/docs/library/entities.md
                - Input:
                    - GetMousePos: lua/docs/library/input/getmousepos.md
                    - IsButtonDown: lua/docs/library/input/isbuttondown.md
                    - IsButtonPressed: lua/docs/library/input/isbuttonpressed.md
                    - IsButtonReleased: lua/docs/library/input/isbuttonreleased.md
                    - GetMouseWheelDelta: lua/docs/library/input/getmousewheeldelta.md
                    - Keylist: lua/docs/library/input/keylist.md
                - Callbacks:
                    - Register: lua/docs/library/callbacks/register.md
                    - Unregister: lua/docs/library/callbacks/unregister.md
                - Common:
                    - Time: lua/docs/library/common/time.md
                    - DecodePNG: lua/docs/library/common/decodepng.md
                    - DecodeJPEG: lua/docs/library/common/decodejpeg.md
                    - RasterizeSVG: lua/docs/library/common/rasterizesvg.md
                - Draw:
                    - Color: lua/docs/library/draw/color.md
                    - Line: lua/docs/library/draw/line.md
                    - FilledRect: lua/docs/library/draw/filledrect.md
                    - OutlinedRect: lua/docs/library/draw/outlinedrect.md
                    - RoundedRect: lua/docs/library/draw/roundedrect.md
                    - RoundedRectFill: lua/docs/library/draw/roundedrectfill.md
                    - ShadowRect: lua/docs/library/draw/shadowrect.md
                    - Triangle: lua/docs/library/draw/triangle.md
                    - FilledCircle: lua/docs/library/draw/filledcircle.md
                    - OutlinedCircle: lua/docs/library/draw/outlinedcircle.md
                    - GetTextSize: lua/docs/library/draw/gettextsize.md
                    - Text: lua/docs/library/draw/text.md
                    - TextShadow: lua/docs/library/draw/textshadow.md
                    - GetScreenSize: lua/docs/library/draw/getscreensize.md
                    - CreateFont: lua/docs/library/draw/createfont.md
                    - AddFontResource: lua/docs/library/draw/addfontresource.md
                    - SetFont: coming-soon.md
                    - CreateTexture: coming-soon.md
                    - UpdateTexture: coming-soon.md
                    - SetTexture: coming-soon.md
                - File:
                    - Open: lua/docs/library/file/open.md
                    - Delete: lua/docs/library/file/delete.md
                    - Enumerate: lua/docs/library/file/enumerate.md
                - Gui:
                    - Coming soon: coming-soon.md
                - HTTP:
                    - Get: lua/docs/library/http/get.md
                - Network:
                    - Socket: coming-soon.md
                    - GetAddrInfo: coming-soon.md
                    - GetNameInfo: coming-soon.md
                - Vector:
                    - Coming soon: coming-soon.md
            - Engine Specific:
                  - Source:
                        - Callbacks: coming-soon.md
                        - Classes:
                            - Trace: lua/docs/engine/source/class/trace.md
                        - Libraries:
                            - Engine:
                                - GetMapName: lua/docs/engine/source/library/engine/getmapname.md
                                - GetPointsContent: lua/docs/engine/source/library/engine/getpointscontent.md
                                - TraceHull: lua/docs/engine/source/library/engine/tracehull.md
                                - TraceLine: lua/docs/engine/source/library/engine/traceline.md
        - Examples: lua/examples.md

theme:
    name: material
    favicon: 'https://aimware.net/favicon.ico'
    palette:
        scheme: slate
        primary: red
        accent: red

plugins:
    - search

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
